### ISSUE TITLE
Rename Zip to Archive, and use Tar rather then Zip on unix platforms

### ISSUE THREAD

**Issue by ThadHouse** [GradleWeaver/simple-jlink#1]
Zip is not safe to use for runtimes on unix platforms. Instead `Tar` with compression enabled should be used. For any functions that need to take both, `AbstractArchiveTask` works.

**Comment by SamCarlberg** [comment]
Fixed on the plugin development branch in a170fb27aab4d238cf13a3e57433d3f6639c601d
